version: "3.4"

services:
  ghost:
    image: ghost:4
    restart: always
    ports:
      - 8100:2368
    depends_on:
      - db
    environment:
      url: https://<domain>
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: ghost
      database__connection__database: ghost
    volumes:
      - ./theme:/var/lib/ghost/content.orig/themes/main
      - ./content:/var/lib/ghost/content
      - ./config.production.json:/var/lib/ghost/config.production.json

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ghost
    volumes:
      - ./data:/var/lib/mysql
