version: "3.4"

services:
  ghost:
    image: ghost:4-alpine
    restart: always
    ports:
      - 8100:2368
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./theme:/var/lib/ghost/content.orig/themes/main
      - ./content:/var/lib/ghost/content

  db:
    image: mariadb:latest
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    env_file:
      - .env
