version: "3.4"

services:
  ghost:
    image: ghost:latest
    restart: always
    depends_on:
      - db
    ports:
      - 8000:2368
    environment:
      url: http://localhost:8000
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: ghost
      database__connection__database: ghost
    volumes:
      - ./content:/var/lib/ghost/content
      - ./theme:/var/lib/ghost/content.orig/themes/main
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
